[build]
publish = "public"
command = "hugo --gc"

[build.environment]
HUGO_VERSION = "0.88.1"

[context.draft]
command = "hugo -b $DEPLOY_PRIME_URL --buildDrafts --buildFuture"

[context.deploy-preview]
command = "hugo -b $DEPLOY_URL"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"

[[redirects]]
from = "/*"
to = "/404/"
status = 404